In [1]:
import sys
import os
%matplotlib inline
# Add the src directory to the Python path
sys.path.append(os.path.abspath('../src'))
from data_prepocessing import split_data, normalize_data
from utils import save_dataframe_as_csv, load_data, set_pandas_options

In [2]:
#loading the dataset
path = '../datasets/raw/housing_prices_boston.csv'
df = load_data(path)

In [4]:
set_pandas_options()

In [5]:
# Removing duplicate and null values
df = df.dropna()
df.drop_duplicates(keep=False)

        CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD  TAX  PTRATIO       B  LSTAT  MEDV
0    0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900    1  296     15.3  396.90   4.98  24.0
1    0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671    2  242     17.8  396.90   9.14  21.6
2    0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671    2  242     17.8  392.83   4.03  34.7
3    0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622    3  222     18.7  394.63   2.94  33.4
5    0.02985   0.0   2.18   0.0  0.458  6.430  58.7  6.0622    3  222     18.7  394.12   5.21  28.7
..       ...   ...    ...   ...    ...    ...   ...     ...  ...  ...      ...     ...    ...   ...
499  0.17783   0.0   9.69   0.0  0.585  5.569  73.5  2.3999    6  391     19.2  395.77  15.10  17.5
500  0.22438   0.0   9.69   0.0  0.585  6.027  79.7  2.4982    6  391     19.2  396.90  14.33  16.8
502  0.04527   0.0  11.93   0.0  0.573  6.120  76.7  2.2875    1  273     21.0  396.90   9.08  20.6
503  0.06076   0.0  11.93   0.0  0.573  6.976  91.0  2.1675    1  273     21.0  396.90   5.64  23.9
504  0.10959   0.0  11.93   0.0  0.573  6.794  89.3  2.3889    1  273     21.0  393.45   6.48  22.0

[394 rows x 14 columns]

In [5]:
#selecting the feature columns 
feature_columns = ['CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'TAX', 'PTRATIO', 'B', 'LSTAT']

#selecting the label column
# label_columns = 'MEDV'

#shuffleing the data before splitting
df = df.sample(frac=1).reset_index(drop=True)

#spiliting the data into x_train, y_train, x_test, y_test
# x_train, x_test, y_train, y_test = split_data(df, feature_columns, label_columns)

In [6]:
normalization_method = 'min_max'
normalize_data(df, normalization_method, feature_columns)

         CRIM    ZN     INDUS  CHAS       NOX        RM       AGE       DIS       RAD       TAX   PTRATIO         B     LSTAT  MEDV
0    0.031607  0.00  0.646628   0.0  0.296680  0.421728  0.385170  0.269958  1.000000  0.914122  0.808511  0.989906  0.239790  21.8
1    0.072359  0.00  0.646628   0.0  0.404564  0.548764  0.740474  0.097373  1.000000  0.914122  0.808511  0.241821  0.284216  16.1
2    0.000579  0.00  0.073314   0.0  0.205394  0.655106  0.571576  0.154534  0.086957  0.011450  0.553191  1.000000  0.091336  37.2
3    0.041220  0.00  0.646628   0.0  0.402490  0.527112  0.504634  0.260264  1.000000  0.914122  0.808511  0.979001  0.244205  21.2
4    0.008489  0.20  0.128666   0.0  0.535270  0.383024  0.616890  0.077922  0.173913  0.146947  0.042553  0.988587  0.240618  22.8
..        ...   ...       ...   ...       ...       ...       ...       ...       ...       ...       ...       ...       ...   ...
389  0.000252  0.28  0.534457   0.0  0.155602  0.507760  0.267765  0.230638  0.130435  0.158397  0.595745  0.998554  0.123620  25.0
390  0.000236  0.00  0.242302   0.0  0.165975  0.547998  0.782698  0.348962  0.043478  0.104962  0.553191  1.000000  0.204470  21.6
391  0.001665  0.25  0.171188   0.0  0.132780  0.495114  0.270855  0.607917  0.304348  0.185115  0.755319  0.984225  0.141556  23.3
392  0.003954  0.00  0.210411   1.0  0.244813  0.649550  0.881565  0.157508  0.304348  0.229008  0.510638  0.986812  0.220199  26.7
393  0.000959  0.00  0.379399   0.0  0.049793  0.479785  0.050463  0.378079  0.130435  0.225191  0.702128  0.984809  0.104581  22.8

[394 rows x 14 columns]

In [6]:
#saving the x_train, y_train, x_test, y_test
# save_dataframe_as_csv(x_train, "../datasets/ready/train/x_train.csv")
# save_dataframe_as_csv(y_train, "../datasets/ready/train/y_train.csv")
# save_dataframe_as_csv(x_test, "../datasets/ready/test/x_test.csv")
# save_dataframe_as_csv(y_test, "../datasets/ready/test/y_test.csv")
save_dataframe_as_csv(df, '../datasets/ready/dataset.csv')